package com.github.cadedi.gateway;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;


// Generated by https://start.springboot.io

@SpringBootApplication
public class MangoGatewayApplication {

    public static void main(String[] args) {
        SpringApplication.run(MangoGatewayApplication.class, args);
    }

}
