server:
  port: 8002
spring:
  application:
    name: mango-backup
  boot:
    # 注册到spring-admin监控服务器
    admin:
      client:
        url: "http://localhost:8000"
# 配置spring-admin监控客户端,默认不开放监控检查接口,以下配置全部开放
management:
  endpoints:
    web:
      exposure:
        include: "*"

# backup datasource
mango:
  backup:
    datasource:
      host: localhost
      userName: root
      password: 123456
      database: mango



